<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Title>Navigation Computer</Title>
    <Version>2.4.1</Version>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AssemblySearchPaths>{HintPathFromItem};$(BattleTechGameDir)\BattleTech_Data\Managed</AssemblySearchPaths>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <PublicizerRuntimeStrategies>Unsafe</PublicizerRuntimeStrategies>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>..\</OutputPath>
  </PropertyGroup>
  <Target Name="CopyFilesToModFolder" AfterTargets="Build">
    <PropertyGroup>
      <ModFolder>$(BattleTechGameDir)\Mods\$(AssemblyName)\</ModFolder>
    </PropertyGroup>
    <ItemGroup>
      <ModFiles Include="$(TargetPath)" />
      <ModFiles Include="$(ProjectDir)..\mod.json" />
      <ModFiles Include="$(ProjectDir)..\README.md" />
    </ItemGroup>
    <Copy SourceFiles="@(ModFiles)" DestinationFolder="$(ModFolder)" SkipUnchangedFiles="false" />
  </Target>
  <ItemGroup>
    <PackageReference Include="HarmonyX" Version="2.13.0">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0" />
    <Publicize Include="Assembly-CSharp" />
  </ItemGroup>
  <ItemDefinitionGroup>
    <Reference>
      <Private>False</Private>
    </Reference>
  </ItemDefinitionGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp" />
    <Reference Include="BEXTimeline">
      <HintPath>$(BattleTechGameDir)\Mods\BT_Extended_Timeline\BEXTimeline.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="UnityEngine" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="Unity.TextMeshPro" />
    <Reference Include="UnityEngine.ParticleSystemModule" />
    <Reference Include="UnityEngine.TextRenderingModule" />
    <Reference Include="UnityEngine.UI" Publicize="true" />
  </ItemGroup>
</Project>